server:
  port: 8081

spring:
  application:
    name: post-service
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:5432/example_database?currentSchema=media_hub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka
  instance:
   instance-id: ${spring.application.name}:${random.uuid}

logging:
  level:
    root: ERROR
    org.springframework: WARN
    org.example: INFO
