server:
  port: 8888

spring:
  application:
    name: github-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/DenysSoldatenko/RestfulBlogApplication.git
          clone-on-start: true
          basedir: test-micro
          username: DenysSoldatenko
          password:
          default-label: master
