server:
  port: 8765

spring:
  application:
    name: gateway-service
  r2dbc:
    url: r2dbc:pool:postgres://${SPRING_DATASOURCE_HOST:localhost}:5432/example_database?currentSchema=media_hub
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    config:
      enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      length: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 36000
  issuer: spring-cloud_project

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: ERROR
    org.springframework: WARN
    org.example: INFO