server:
  port: 8085

spring:
  application:
    name: quiz-service
  cloud:
    config:
      enabled: false
  data:
    elasticsearch:
      repositories:
       enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

quiz-service:
  elasticsearch:
    host: ${SPRING_DATASOURCE_HOST:localhost}

logging:
  level:
    root: ERROR
    org.springframework: WARN
    org.example: INFO