server:
  port: 8085

spring:
  application:
    name: app-quiz
  cloud:
    config:
      enabled: false
  data:
    elasticsearch:
      repositories:
       enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

logging:
  level:
    root: ERROR
    org.springframework: WARN
    org.example: INFO