server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
