spring:
  application:
    name: app-blog
  datasource:
    url: jdbc:postgresql://localhost:5432/example_database?currentSchema=media_hub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false

server:
  port: 8081

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka
  instance:
   instance-id: ${spring.application.name}:${random.uuid}

logging:
  level:
    org.springframework.security: DEBUG
