spring:
  application:
    name: data-generator
  datasource:
    url: jdbc:postgresql://localhost:5432/example_database?currentSchema=media_hub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: DEBUG
